### ISSUE TITLE
Instances for Vector Bit

### ISSUE THREAD

**Issue by Bodigrim** [haskell-works/hw-rankselect-base#20]
Would it be appropriate to prepare a PR, adding `Rank{0,1}` and `Select{0,1}` instances for `Vector Data.Bit.Bit` from [`bitvec`](http://hackage.haskell.org/package/bitvec) package? I intend to use [`nthBitIndex`](http://hackage.haskell.org/package/bitvec-1.0.2.0/docs/Data-Bit.html#v:nthBitIndex) and [`countBits`](http://hackage.haskell.org/package/bitvec-1.0.2.0/docs/Data-Bit.html#v:countBits).

**Comment by newhoggy** [comment]
Sure!
